version: "3.9"

services:
  userdb:
    container_name: user_database
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database-utenti
    ports:
      - "3307:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p password",
        ]
      timeout: 20s
      retries: 15

  securitydb:
    container_name: security_database
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database-sicurezza
    ports:
      - "3308:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p password",
        ]
      timeout: 15s
      retries: 15

  blue-whale:
    container_name: gatewayB
    build:
      context: ./backend-gateway
      dockerfile: "Dockerfile"
    ports:
      - "8080:8080"


  sleepin-cat:
    container_name: usersB
    build:
      context: ./backend-gestione-utenti
      dockerfile: "Dockerfile"
    depends_on:
      userdb:
        condition: service_healthy
    ports:
      - "8082:8082"

  honeybear:
    container_name: securityB
    build:
      context: ./backend-login
      dockerfile: "Dockerfile"
    depends_on:
      securitydb:
        condition: service_healthy
    ports:
      - "8081:8081"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: "Dockerfile"
    ports:
      - "3000:3000"
